#!/bin/bash
#### PiFire - A pellet grill/smoker management utility.
####
#### PiFire is written by Ben Parmeter aka nebhead
#### Copyright 2020 - 2023
#### https://github.com/nebhead/PiFire
####
#### PiFireOS build files written by Kyle Menigoz aka CalonMerc
#### Based on the fantastic work of CustomPiOS by Guy Sheffer aka guysoft
####
#### This File is distributed under MIT License
####
set -x
set -e

export LC_ALL=C

source /common.sh

# Set /tmp to RAM based storage in /etc/fstab 
echo "tmpfs /tmp  tmpfs defaults,noatime 0 0" | sudo tee -a /etc/fstab > /dev/null
#update aptitude packages
apt update
#upgrade aptitude packages
apt upgrade -y

#install dependencies
apt install python3-dev python3-pip python3-venv python3-rpi.gpio python3-scipy nginx git supervisor ttf-mscorefonts-installer redis-server libatlas-base-dev libopenjp2-7 -y

#set up pifire group
groupadd pifire
usermod -aG pifire $BASE_USER
usermod -aG pifire root

du -h --max-depth 1 /usr 2>/dev/null | sort -h -r | tail -10
# clean up image
rm -rv /opt/*
rm -rv /usr/share/icons/*
rm -rv /usr/games/
rm -rv /usr/share/sounds/

du -h --max-depth 1 /usr 2>/dev/null | sort -h -r | tail -10

# Download PiFire
pushd ${PIFIRE_INSTALL_PATH}
    if [ "${PIFIRE_REPO_BRANCH}" == "master" ]; then
        git clone --depth 1 $PIFIRE_REPO_URL pifire
    else
        git clone --depth 1 --branch $PIFIRE_REPO_BRANCH $PIFIRE_REPO_URL pifire
    fi
    # Change ownership to group=pifire for all files/directories in pifire 
    chown -R $BASE_USER:pifire pifire
    # Change ability for pifire group to read/write/execute 
    chmod -R 775 pifire
    #set up Python VENV
    python -m venv --system-site-packages pifire
    pushd pifire
        source bin/activate 
        # Install module dependencies 
        python -m pip install "flask==2.3.3" 
        python -m pip install flask-mobility
        python -m pip install flask-qrcode
        python -m pip install flask-socketio
        python -m pip install eventlet
        python -m pip install gunicorn
        python -m pip install gpiozero
        python -m pip install redis
        python -m pip install uuid
        python -m pip install influxdb-client[ciso]
        python -m pip install apprise
        python -m pip install scikit-fuzzy
        python -m pip install scikit-learn
        python -m pip install ratelimitingfilter
        python -m pip install "pillow>=9.2.0"
        python -m pip install paho-mqtt
        python -m pip install psutil
    
        #configure  auto-install scripts
        pushd auto-install
            #copy Nginx file(s)
            rm /etc/nginx/sites-enabled/default
            cp nginx/pifire.nginx /etc/nginx/sites-available/pifire
            ln -s /etc/nginx/sites-available/pifire /etc/nginx/sites-enabled

            #copy Supervisor file(s)
            cp supervisor/*.conf /etc/supervisor/conf.d/
        popd
    popd
popd

#configure Supervisor
if [[ ${PIFIRE_SUPERVISORD_ENABLE_UI} = "ENABLE_SVISOR" ]];then
   echo " " | sudo tee -a /etc/supervisor/supervisord.conf > /dev/null
   echo "[inet_http_server]" | sudo tee -a /etc/supervisor/supervisord.conf > /dev/null
   echo "port = 9001" | sudo tee -a /etc/supervisor/supervisord.conf > /dev/null
   echo "username = " ${PIFIRE_SUPERVISORD_DEFAULT_USER} | sudo tee -a /etc/supervisor/supervisord.conf > /dev/null
   echo "password = " ${PIFIRE_SUPERVISORD_DEFAULT_PASS} | sudo tee -a /etc/supervisor/supervisord.conf > /dev/null
fi

# Configure SPI, i2c, and misc for screens

# echo "dtparam=spi=on" | tee -a /boot/config.txt > /dev/null
raspi-config nonint do_spi 0
# echo "dtparam=i2c_arm=on" | tee -a /boot/config.txt > /dev/null
# echo "i2c-dev" | tee -a /etc/modules > /dev/null
raspi-config nonint do_i2c 0
# Enable Hardware PWM - Needed for hardware PWM support 
if test -f /boot/firmware/config.txt; then
  echo "dtoverlay=pwm,gpiopin=13,func=4" | tee -a /boot/firmware/config.txt > /dev/null
else
  echo "dtoverlay=pwm,gpiopin=13,func=4" | tee -a /boot/config.txt > /dev/null
fi
echo 'SUBSYSTEM=="backlight",RUN+="/bin/chmod 666 /sys/class/backlight/%k/brightness /sys/class/backlight/%k/bl_power"' | tee -a /etc/udev/rules.d/backlight-permissions.rules > /dev/null
